### ISSUE TITLE
selection problem

### ISSUE THREAD

**Issue by rorschach217** [3stack-software/meteor-blaze-datetimepicker#1]
## when celender box opens above text box its not working.  

i.e. if box appears above text box its not letting click on any months or any thing
![screen shot 2016-08-10 at 12 20 38 pm](https://cloud.githubusercontent.com/assets/16304590/17544467/11293036-5ef5-11e6-965f-1edba1d78b1b.png)

**Comment by nathan-muir** [comment]
Hey,

This is just a helper function that initialises the datetime picker from https://github.com/tsega/meteor-bootstrap3-datetimepicker/  (which wraps https://github.com/Eonasdan/bootstrap-datetimepicker )

So the issue you're having probably has nothing to do with this package.
